FROM debian:stretch-slim

ENV CHAIN <%= chain %>
ENV VERSION <%= version %>
ENV URL <%= url %>
ENV SHA256 <%= sha256 %>
ENV PORT_P2P <%= p2p_port %>
ENV PORT_RPC <%= rpc_port %>
ENV PORT_P2PTESTNET <%= testnet_p2p_port %>
ENV PORT_RPCTESTNET <%= testnet_rpc_port %>
ENV DATA_FOLDER /data

<% if asc_url -%>
ENV ASC_URL <%= asc_url %>
ENV PGP_KEY <%= key %>
<% end -%>

<% case chain when "bitcoin" -%>
	ENV DEFAULT_FOLDER /home/bitcoin/.bitcoin
<% when "litecoin" -%>
	ENV DEFAULT_FOLDER /home/litecoin/.litecoin
<% when "dcr" -%>
	ENV DEFAULT_FOLDER /root/.dcrd
<% end -%>

RUN groupadd -r "$CHAIN" && useradd -r -m -g "$CHAIN" "$CHAIN"

RUN set -ex \
	&& apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg wget \
	&& rm -rf /var/lib/apt/lists/*

# install node binaries
RUN set -ex \
	&& cd /tmp \
	&& wget -qO "$CHAIN.tar.gz" "$URL" \
	&& echo "$SHA256 $CHAIN.tar.gz" | sha256sum -c - \
<% if asc_url -%>
	&& gpg --keyserver keyserver.ubuntu.com --recv-keys "$PGP_KEY" \
	&& wget -qO "$CHAIN.asc" "$ASC_URL" \
	&& gpg --verify "$CHAIN.asc" \
<% end -%>
	&& tar -xzvf "$CHAIN.tar.gz" -C /usr/local --strip-components=1 --exclude=*-qt \
	&& rm -rf /tmp/*

# create data directory
RUN mkdir -p "$DATA_FOLDER" \
	&& mkdir -p "$DEFAULT_FOLDER" \
	&& chown -R "$CHAIN:$CHAIN" "$DATA_FOLDER" \
	&& ln -sfn "$DATA_FOLDER" "$DEFAULT_FOLDER" \
	&& chown -h "$CHAIN:$CHAIN" "$DEFAULT_FOLDER"
VOLUME "$DATA_FOLDER"


EXPOSE "$PORT_P2P" "$PORT_RPC" "$PORT_P2PTESTNET" "$PORT_RPCTESTNET"

<% case chain when "bitcoin", "litecoin" -%>
	COPY docker-entrypoint.sh /entrypoint.sh
	ENTRYPOINT ["/entrypoint.sh"]
	CMD "$CHAIN"d
<% when "dcr" -%>
	CMD usr/local/resources/bin/dcrd
<% end -%>
