FROM debian:stretch-slim

ENV NODECHAIN <%= branch %>
ENV NODEVERSION <%= version %>
ENV NODEURL <%= url %>
ENV NODESHA256 <%= sha256 %>
<% if asc_url -%>
ENV NODEASC_URL <%= asc_url %>
ENV NODEPGP_KEY <%= key %>
<% end -%>

<% case branch when "bitcoin" %> 
	ENV NODEPORT_P2P 8332
	ENV NODEPORT_RPC 8333
	ENV NODEPORT_P2PTESTNET 18332
	ENV NODEPORT_RPCTESTNET 18333
<% when "litecoin" %>
	ENV NODEPORT_P2P 9332
	ENV NODEPORT_RPC 9333
	ENV NODEPORT_P2PTESTNET 19332
	ENV NODEPORT_RPCTESTNET 19333
<% when "dcr" %>
	ENV NODEPORT_P2P 9108
	ENV NODEPORT_RPC 9109
	ENV NODEPORT_P2PTESTNET 19108
	ENV NODEPORT_RPCTESTNET 19109
<% end %>

RUN groupadd -r "$NODECHAIN" && useradd -r -m -g "$NODECHAIN" "$NODECHAIN"

RUN set -ex \
	&& apt-get update \
	&& apt-get install -qq --no-install-recommends dialog ca-certificates dirmngr gosu gpg wget \
	&& rm -rf /var/lib/apt/lists/*

# install "$NODECHAIN" binaries
RUN set -ex \
	&& cd /tmp \
	&& wget -qO "$NODECHAIN.tar.gz" "$NODEURL" \
	&& echo "$NODESHA256 $NODECHAIN.tar.gz" | sha256sum -c - \
<% if asc_url -%>
	&& gpg --keyserver keyserver.ubuntu.com --recv-keys "$NODEPGP_KEY" \
	&& wget -qO "$NODECHAIN.asc $NODEASC_URL" \
	&& gpg --verify "$NODECHAIN.asc" \
<% end -%>
	&& tar -xzvf "$NODECHAIN.tar.gz" -C /usr/local --strip-components=1 --exclude=*-qt \
	&& rm -rf /tmp/*

# create data directory
ENV NODEDATA /data
RUN mkdir "$NODEDATA" \
	&& chown -R "$NODECHAIN:$NODECHAIN" "$NODEDATA" \
	&& ln -sfn "$NODEDATA" "/home/$NODECHAIN/.$NODECHAIN" \
	&& chown -h "$NODECHAIN:$NODECHAIN" "/home/$NODECHAIN/.$NODECHAIN"
VOLUME /data

COPY docker-entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE "$NODEPORT_P2P" "$NODEPORT_RPC" "$NODEPORT_P2PTESTNET" "$NODEPORT_RPCTESTNET"

CMD ${NODECHAIN}d
